name: Expense Tracker CI/CD

on:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main", "develop"]
  workflow_dispatch:
    branches: [ "main", "develop"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Get source Code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install libpq-dev
      run: |
        sudo apt install libpq-dev

    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run Tests
      env:
        SECRET_KEY: _07(&087^%$^^&RR9y8h6#$6^NNjt4io@nh
        DEBUG: 1
        ALLOWED_HOSTS: http://localhost:8000
  
      run: |
        pytest -p no:warnings

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
